source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def pods
  pod 'SnapKit'               # Masonry
  pod 'Alamofire'             # afnetworking
  pod 'KakaJSON'              # MJExtension
  pod 'Kingfisher'            # SDWebImage
  
  pod 'MJRefresh', '~> 3.4.3'
  pod 'WechatOpenSDK', '~> 1.8.7.1'
  pod 'IQKeyboardManager'
  pod 'SVProgressHUD'
  pod 'FMDB'
end

target 'FRLawlib' do
    pods
end

